### ISSUE TITLE
Copying index when a JSONB index is present on a table is still broken

### ISSUE THREAD

**Issue by cmer** [fatkodima/online_migrations#40]
I've been able to identify the root cause of the issue and I have a PR coming.

I have another column on my table that includes the name of the column I'm actually trying to copy the index for, and that column is JSONB. For example, I am trying to copy the index for `foo` but I also have a JSONB column named `foo_bar`. The `foo_bar` column has a JSONB index, which Rails interprets as plain text rather than an array. See:

```
          #<ActiveRecord::ConnectionAdapters::IndexDefinition:0x00000001205e9748
          # @columns="(((foo_bar -> 'session'::text) ->> 'note'::text))",
          # @comment=nil,
          # @lengths={},
          # @name="index_notes_on_foo_bar_note",
          # @opclasses={},
          # @orders={},
          # @table="notes",
          # @type=nil,
          # @unique=false,
          # @using=:btree,
          # @where=nil>]
```

`online_migrations` assumes `#columns` is always an array, but in this case it is a String. We should only handle arrays.

**Comment by fatkodima** [comment]
Can you share the table schema and what column you are trying to change?

**Comment by cmer** [comment]
DM'd you @ X.

**Comment by fatkodima** [comment]
I think I got the problem. So is the problem is that the irrelevant index is recreated needlessly or is there some error generated? 

Unfortunately, we cannot skip non-array columns. For example, consider
```ruby
create_table :users do |t|
  t.string :email
  t.index "lower(email)"
end
```

If we decide to change the `email`'s type, in the process of doing so we create a new column and must copy all the old indexes. If we skip non array ones (like for expression indexes where we get a string for `columns`), then the new column won't have a `lower(email)` index.

So, yeah, my approach produces false positives, as seen from your example. But this should be rare and I do not know how to handle this elegantly (maybe introduce some option to provide which indexes to copy). Suggestions are welcome.

**Comment by cmer** [comment]
I see what you're saying. The problem though is that it'd try to pick up that index if you were trying to migrate a column named `em`, for example. Perhaps it should regexp on String with a start/end word delimiter? `\bemail\b` kind of thing?

**Comment by fatkodima** [comment]
Yes, good idea. But this can still generate false positives, but more rarely, of course. Will this work for you?

**Comment by cmer** [comment]
I’ll try it tomorrow to see if it works. Thanks!

**Comment by cmer** [comment]
I pushed another commit which seems to work!
