### ISSUE TITLE
Should we disallow `IF NOT EXISTS` for concurrent index creation? 

### ISSUE THREAD

**Issue by ENewmeration** [fatkodima/online_migrations#60]
Two questions:

* should we disallow `IF NOT EXISTS`/`if_not_exists` option for concurrent index creation? Or some means of verifying a valid version of index is already created if we do use that i.e. a specific method for `add_index_concurrently` that does this before adding? I realized we were doing this in our application in some migrations and were exposed to the issue described here: https://www.shayon.dev/post/2024/225/stop-relying-on-if-not-exists-for-concurrent-index-creation-in-postgresql/
Not sure I agree on the retry approach in here so trying to understand a means of protecting against the concern, if we can here

* do you think it's best practice to enforce idempotency for new columns? Like is the first ok or should second be enforced?
```
# ok in one migration?
class AddColumnIdWithIndexToTables < ActiveRecord::Migration[7.1]
  disable_ddl_transaction!

  def change
    add_column :tables, :column_id, :string
    add_index :tables, :column_id, algorithm: :concurrently
  end
end

# maybe better as two?
class AddColumnIdToTables < ActiveRecord::Migration[7.1]
  def change
    add_column :tables, :column_id, :string
  end
end

class AddColumnIdIndexToTables < ActiveRecord::Migration[7.1]
  disable_ddl_transaction!

  def change
    add_index :tables, :column_id, algorithm: :concurrently
  end
end
```

**Comment by fatkodima** [comment]
1. 
`add_index_concurrently` already does some idempotency checks to not create an index if it exists https://github.com/fatkodima/online_migrations/blob/0ff8a59df5c0d09214f6931735a276e94e51951b/lib/online_migrations/background_schema_migrations/migration_helpers.rb#L13-L25
Behind the scenes, when the index is created, it also checks if the invalid index exists and recreates a new one https://github.com/fatkodima/online_migrations/blob/0ff8a59df5c0d09214f6931735a276e94e51951b/lib/online_migrations/background_schema_migrations/migration.rb#L184-L196

I would probably not disallow `IF NOT EXISTS`, because the rails's `index_exists?` method which is used in the code I linked, is not able to properly compare, for example, partial indexes with `:where` clauses, because postgres can normalize what you passed there when creating an index and it won't match the original `:where` value when compared.

And you can always retry index creation if invalid index was created by using - https://github.com/fatkodima/online_migrations/blob/0ff8a59df5c0d09214f6931735a276e94e51951b/lib/online_migrations/background_schema_migrations/migration.rb#L133


2. I think it is easier as two, because you do not need to remember to make `add_column` idempotent

**Comment by ENewmeration** [comment]
sweet, appreciate the quick response thank you!
